#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BUNDLE_DIR=""
OPENPI_DIR="$ROOT_DIR"
ENV_NAME="condapi-yam"
FORCE=0

usage() {
  cat <<EOF
Usage: $(basename "$0") --bundle-dir DIR [--openpi-dir DIR] [--env-name NAME] [--force]

Install the offline bundle into a non-container conda environment on the training server.

Required:
  --bundle-dir DIR   Directory generated by build_offline_bundle.sh

Optional:
  --openpi-dir DIR   Server-side openpi repo to install in editable mode
  --env-name NAME    Target conda env name, default: condapi-yam
  --force            Remove any existing env with the same name first
EOF
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "[err] missing required command: $1" >&2
    exit 1
  fi
}

find_conda_sh() {
  if [ -n "${CONDA_EXE:-}" ] && [ -x "${CONDA_EXE}" ]; then
    local conda_base
    conda_base="$("$CONDA_EXE" info --base)"
    echo "$conda_base/etc/profile.d/conda.sh"
    return 0
  fi

  if command -v conda >/dev/null 2>&1; then
    local conda_base
    conda_base="$(conda info --base)"
    echo "$conda_base/etc/profile.d/conda.sh"
    return 0
  fi

  local candidate
  for candidate in \
    "$HOME/miniconda3/etc/profile.d/conda.sh" \
    "$HOME/miniforge3/etc/profile.d/conda.sh" \
    "$HOME/anaconda3/etc/profile.d/conda.sh"
  do
    if [ -f "$candidate" ]; then
      echo "$candidate"
      return 0
    fi
  done

  return 1
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --bundle-dir)
      BUNDLE_DIR="$2"
      shift 2
      ;;
    --openpi-dir)
      OPENPI_DIR="$2"
      shift 2
      ;;
    --env-name)
      ENV_NAME="$2"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[err] unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ -z "$BUNDLE_DIR" ]; then
  echo "[err] --bundle-dir is required" >&2
  usage >&2
  exit 1
fi

CONDA_SH="$(find_conda_sh)"
if [ ! -f "$CONDA_SH" ]; then
  echo "[err] could not locate conda.sh" >&2
  exit 1
fi
source "$CONDA_SH"

require_cmd conda

META_DIR="$BUNDLE_DIR/meta"
CONDA_PKGS_DIR="$BUNDLE_DIR/conda_pkgs"
WHEELHOUSE_DIR="$BUNDLE_DIR/wheelhouse"
CONDA_PACKAGE_LIST="$META_DIR/conda-package-basenames.txt"
PIP_REQ_FILE="$META_DIR/requirements-pi-pip.txt"

for path in "$META_DIR" "$CONDA_PKGS_DIR" "$WHEELHOUSE_DIR" "$CONDA_PACKAGE_LIST" "$PIP_REQ_FILE"; do
  if [ ! -e "$path" ]; then
    echo "[err] missing bundle path: $path" >&2
    exit 1
  fi
done

if [ ! -d "$OPENPI_DIR" ]; then
  echo "[err] openpi dir not found: $OPENPI_DIR" >&2
  exit 1
fi

if ! conda env list | awk '{print $1}' | grep -Fxq "$ENV_NAME"; then
  :
elif [ "$FORCE" -eq 1 ]; then
  echo "[info] removing existing env: $ENV_NAME"
  conda env remove -y -n "$ENV_NAME"
else
  echo "[err] conda env already exists: $ENV_NAME (use --force to replace)" >&2
  exit 1
fi

TMP_EXPLICIT="$(mktemp "${TMPDIR:-/tmp}/pi-conda-explicit.XXXXXX")"
trap 'rm -f "$TMP_EXPLICIT"' EXIT
{
  echo "@EXPLICIT"
  while IFS= read -r pkg; do
    [ -n "$pkg" ] || continue
    echo "file://$CONDA_PKGS_DIR/$pkg"
  done < "$CONDA_PACKAGE_LIST"
} > "$TMP_EXPLICIT"

echo "[info] creating conda env from offline explicit package list"
conda create -y -n "$ENV_NAME" --offline --file "$TMP_EXPLICIT"

echo "[info] installing Python wheels from offline wheelhouse"
conda run -n "$ENV_NAME" python -m pip install \
  --no-index \
  --find-links "$WHEELHOUSE_DIR" \
  -r "$PIP_REQ_FILE"

echo "[info] installing lerobot and dlimp wheels"
conda run -n "$ENV_NAME" python -m pip install \
  --no-deps \
  --no-index \
  --find-links "$WHEELHOUSE_DIR" \
  lerobot dlimp

echo "[info] installing openpi-client and openpi from local repo"
conda run -n "$ENV_NAME" python -m pip install \
  --no-build-isolation \
  --no-deps \
  -e "$OPENPI_DIR/packages/openpi-client"

conda run -n "$ENV_NAME" python -m pip install \
  --no-build-isolation \
  --no-deps \
  -e "$OPENPI_DIR"

echo "[info] applying transformers patch overlay"
conda run -n "$ENV_NAME" python "$OPENPI_DIR/scripts/conda/patch_transformers.py" --openpi-dir "$OPENPI_DIR"

echo "[ok] offline conda environment installed: $ENV_NAME"
echo "[ok] smoke-test imports:"
conda run -n "$ENV_NAME" python - <<PY
import openpi
import openpi_client
import transformers
import jax
import torch
print("openpi", openpi.__file__)
print("openpi_client", openpi_client.__file__)
print("transformers", transformers.__version__)
print("jax", jax.__version__)
print("torch", torch.__version__)
PY
