name: Test
on:
  pull_request:
    branches:
      - "*"

jobs:
  run_tests:
    name: Run Tests
    runs-on: openpi-verylarge
    env:
      GIT_LFS_SKIP_SMUDGE: true
    steps:
      - uses: actions/checkout@v4

      - name: Install FFmpeg dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libavcodec-dev libavformat-dev libavutil-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install the project
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r scripts/conda/requirements-pi-pip.txt
          python -m pip install --no-build-isolation --no-deps -e packages/openpi-client
          python -m pip install --no-build-isolation --no-deps -e .

      - name: Run tests
        run: python -m pytest --strict-markers -m "not manual"
